### PR TITLE
Minor issues

### PR DESCRIPTION
**Pull request by adius**
Hi,

there were some typos and bugs in your code.
I took the liberty to fix them for you. 😉

Well, actually, [Feram] did it.
It’s a tool that we developed to fix our own code.
If you want to use it as well, it’s really simple to integrate:
[feram.io/help/getting-started]

Hope you like it! 😁

[Feram]: http://feram.io
[feram.io/help/getting-started]: https://feram.io/help/getting-started

### CODE REVIEW

**Comment by nickgravelyn** [comment]
Sorry but this is just style changes I don’t want to take.

**Comment by adius** [comment]
Sure, but I'd strongly recommend it: https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

**Comment by nickgravelyn** [comment]
I totally get trailing commas, but I'm currently testing out StandardJS which enforces no trailing commas, so this style change will just be immediately flagged as a linter error in my current tooling. I may change that at some point but that's how it is right now.

**Comment by adius** [comment]
WHAT? I wasn't aware that standard.js does not support trailing commas.
They have many reasonable style choices so I assumed they would of course also enforce trailing commas. That's just sad. 😩

We use https://github.com/style-guides/JavaScript at @feramhq. With trailing commas and better if else formatting. I think otherwise it's the same as standardjs by now. Feel free to join us ;-)
As it is a eslint plugin, it works just out of the box if you have eslint enabled in your editor...

**Pull request closed without merging**
